In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('emp.csv')

In [3]:
df.shape

(15, 11)

In [4]:
df.isnull().sum()

customer_id           0
age                   0
income                2
credit_score          2
loyalty_tier          0
education             0
employment_status     0
preferred_category    0
state                 0
is_subscribed         0
churn                 0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(11, 11)

In [10]:
df.isnull().sum()

customer_id           0
age                   0
income                0
credit_score          0
loyalty_tier          0
education             0
employment_status     0
preferred_category    0
state                 0
is_subscribed         0
churn                 0
dtype: int64

In [11]:
df.head()

,customer_id,age,income,credit_score,loyalty_tier,education,employment_status,preferred_category,state,is_subscribed,churn
0,CUST_101,28,45000.0,650.0,Silver,Bachelor,Employed,Electronics,MH,1,0
1,CUST_102,45,82000.0,720.0,Gold,Master,Employed,Clothing,DL,1,0
2,CUST_103,19,12000.0,580.0,Bronze,High School,Student,Electronics,UP,0,1
4,CUST_105,52,115000.0,780.0,Platinum,Doctorate,Self-Employed,Books,MH,1,0
6,CUST_107,41,67000.0,610.0,Silver,Master,Employed,Electronics,KA,1,0

In [12]:
df.sample(5)

,customer_id,age,income,credit_score,loyalty_tier,education,employment_status,preferred_category,state,is_subscribed,churn
12,CUST_113,31,52000.0,670.0,Silver,Bachelor,Employed,Electronics,TN,1,0
10,CUST_111,50,140000.0,810.0,Platinum,Doctorate,Employed,Home & Kitchen,DL,1,0
7,CUST_108,60,95000.0,740.0,Platinum,Master,Retired,Home & Kitchen,TN,1,0
1,CUST_102,45,82000.0,720.0,Gold,Master,Employed,Clothing,DL,1,0
4,CUST_105,52,115000.0,780.0,Platinum,Doctorate,Self-Employed,Books,MH,1,0

In [14]:
df['education'].unique()

array(['Bachelor', 'Master', 'High School', 'Doctorate'], dtype=object)